### ISSUE TITLE
BrainGlobe tutorials for neuroscientists

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/BrainGlobe#11]
We would like some tutorials that show neuroscientists how to do a typical analysis/workflow using `napari`. (e.g. [brainreg-segment](https://docs.brainglobe.info/brainreg-segment/applications/silicon-probe-tracking))
- [ ] decide what workflows each these tutorials should contain?
- [ ] decide on a format (video showing someone using napari? Jupyter notebook?)
- [ ] actually make them

**Comment by adamltyson** [comment]
Closing in favour of https://github.com/brainglobe/brainglobe.github.io/issues/89
