### ISSUE TITLE
Simplifying the BrainGlobe (meta-)package structure for users and developers

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/BrainGlobe#20]
Currently, the BrainGlobe tools are split into 35 different repositories (not all of which are to be used by users directly), which
- makes searching for what package to install hard for users
- makes CI and testing for interdependent packages hard

We'd like to address this by
 - [x] #13, so users can have a one-line install `conda install -c conda-forge brainglobe` that includes all up-to-date tools
 - [x] do the equivalent for pypi (if possible?), so users can do `pip install brainglobe` with an optional `napari` dependency if needed: `pip install brainglobe[napari]`

This has the additional advantage that we can hide changes in the repo structure from users. So once this is done, we'd like to 
- [ ] #3 
- [ ] #4 
- [ ] #6 

in order to make CI and testing between closely related repos easier.

### Possibly useful resources around Python Packaging

  - [pyopensci package guide](https://www.pyopensci.org/python-package-guide/)
  - [Creating an open source python project from scratch](https://jacobtomlinson.dev/series/creating-an-open-source-python-project-from-scratch/)
  - [Conda forge docs to add packages](https://conda-forge.org/docs/maintainer/adding_pkgs.html)
  - [SeptembRSE talk about Python wheels](https://www.youtube.com/watch?v=FpIJ7T1Gpjo&t=1640s)

**Comment by alessandrofelder** [comment]
@adamltyson the above is initial draft for a meta-issue for @willGraham01 to work on once he joins. Comments welcome.

**Comment by adamltyson** [comment]
All looks good. We have the [brainglobe name on PyPI](https://pypi.org/project/brainglobe/#description). This package was eventually renamed [bg-atlasapi](https://github.com/brainglobe/bg-atlasapi).

> do the equivalent for pypi (if possible?)

I think it's possible, even it it's just:
- A `pyproject.toml` file that has all the other packages as requirements
- An empty `__init__`

This would also allow us to do things like:
**__init__.py**
```python 
from cellfinder_core.main import main as cell_detector_3D
from brainreg.main import main as register_whole_brain
```

**Usage**
```python
import brainglobe as bg

bg.cell_detector_3D()
bg.register_whole_brain()
```

Then in later versions, we can completely restructure the underlying packages.

**Comment by adamltyson** [comment]
Superceeded by #33
