### ISSUE TITLE
[Feature] Tensorflow will be an optional dependency due to conda-forge issues

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/BrainGlobe#27]
See [issue on `conda-forge/cellfinder-core`](https://github.com/conda-forge/cellfinder-core-feedstock/issues/13) for context. 

**Is your feature request related to a problem? Please describe.**
Any package with a hard dependency on tensorflow cannot be installed via `conda-forge`. This primarily affects the `cellfinder-core` package, but also it's dependents (`cellfinder-napari`, `cellfinder`, and thus the meta-package).

These packages will thus be updated to make `tensorflow` an optional dependency. `pip` will be able to install the optional `tensorflow` features because `tensorflow` is available from `pip`, and `conda` will have to make do with the "base" packages.

**Describe the solution you'd like**

1. `cellfinder-core` needs to be updated with an optional `tensorflow` dependency. https://github.com/brainglobe/cellfinder-core/pull/186
    - [x] `__init__.py` will need to check whether the tensorflow dependency is available, and set an internal flag.
    - [x] `tensorflow`-dependent code will need to check this internal flag before running. From this, we will be able to create a complete list of all `cellfinder-core` features that depend on the `tensorflow` install.
    - [x] The package will need to be re-uploaded as a new version to `PyPI`. Whilst not a breaking change, the install instructions will need to be clearly updated to indicate that `tensorflow` needs to be explicitly requested.
2. Packages that are dependent on `cellfinder-core` will also need to be updated to be compatible with or without `tensorflow`.
    - [x] Change `cellfinder-core` to have an optional `tensorflow` dependency that can be requested when `pip`-installing.
    - [ ] `cellfinder-napari` updated | [Pending CI fix](https://github.com/brainglobe/cellfinder-napari/pull/168) | Then tag new version
    - [ ] `cellfinder` updated | [Pending package update](https://github.com/brainglobe/cellfinder/pull/247) | Then tag new version
    - [ ] [`brainglobe-meta` updated](https://github.com/brainglobe/brainglobe-meta/pull/24)
3. `conda-forge` recipes for all concerned packages will need to be updated.
    - [ ] [`cellfinder-core`](https://github.com/conda-forge/cellfinder-core-feedstock/pull/17)
    - [ ] `cellfinder-napari`
    - [ ] `cellfinder` (not on `conda-forge` yet, and proposed to be removed so maybe un-necessary).
    - [ ] `brainglobe-meta` (in staging)

**Describe alternatives you've considered**
See [issue on `conda-forge/cellfinder-core`](https://github.com/conda-forge/cellfinder-core-feedstock/issues/13).

Alternative is we keep things as they are on `PyPI`, and put "broken" packages on `conda-forge` that require Windows users to manually install `tensorflow` first.

@adamltyson just to double-check this all looks good before I commit changes to multiple packages across the whole organisation.

**Comment by adamltyson** [comment]
Yeah sounds good. Presumably the pip metapackage could install `cellfinder-core[tensorflow]`, it would just be the conda metapackage that would require the extra step?

**Comment by willGraham01** [comment]
> Presumably the pip metapackage could install cellfinder-core[tensorflow], it would just be the conda metapackage that would require the extra step?

Yeah, the plan will be
```sh
pip install brainglobe
```
to fetch `cellfinder-core[tensorflow]` (& the others with tensorflow included).

Meanwhile, the conda instructions will be

"Manually download and install tensorflow in your environment, then run
```sh
conda install brainglobe
```
which will install the packages without fetching tensorflow. But the `__init__.py`'s will pickup on the manual install provided the correct environment is activated, so users will still be able to get full functionality.

**Comment by adamltyson** [comment]
Sounds good. Thanks @willGraham01!

**Comment by willGraham01** [comment]
> Include these packages (but no tensorflow) in the brainglobe conda package. This way, all the other tools will work, but users will get a warning if they try to use cellfinder-based tools?

The question is whether it's worth providing `cellfinder` in the `conda` package at all if we're not including `tensorflow`. We can provide a warning in for example `brainglobe-meta`'s `__init__.py`:
```python
try:
    TF_VERSION = version("tensorflow")
    TF_PRESENT = True
except PackageNotFoundError as e:
    TF_PRESENT = False
    # helpful message about tensorflow not being there, so cellfinder is unavailable

if TF_PRESENT:
   # expose cellfinder tools to the user
else:
   # do nothing? Or maybe import some functions that we can alias to play the role of "cellfinder" which just throw warnings and exit when invoked
```
and this way, we don't need to touch any code in the `cellfinder`, `cellfinder-core`, etc packages. And then if users really want `cellfinder`, they can `pip` install `brainglobe` as you say.

Only difference is in the niche case where someone `conda install`s brainglobe, then manually installs `tensorflow`. In which case, the new plan still wouldn't let them use `cellfinder` since conda wouldn't ship it at all. But the old plan of adding guards around all the `cellfinder` source functions would.

**Comment by willGraham01** [comment]
> Can we get the conda metapackage to ship a tensorflow-less cellfinder?

We can; then the next question is what do we want to allow in the event of no `tensorflow`. 
- We can try and keep as many `cellfinder` functions working as possible [(as in here)](https://github.com/brainglobe/cellfinder-core/pull/185): IE guards around _all_ functions that need `tensorflow`. But the main `cellfinder` tools all fall into this category, so anything users actually want to use would be unusable anyway.
- We can just forbid `cellfinder` import without `tensorflow` present on the system? IE in `cellfinder/__init__.py`:
```python
try:
   TF_VERSION = version("tensorflow")
except PackageNotFoundError as e:
   raise PackageNotFoundError(
       f"cellfinder tools cannot be invoked without tensorflow."
       f"Please install tensorflow into your environment to use cellfinder tools."
       f"For more information, please see [RELEVANT LINK TO BG-META DOCS]."
   ) from e
``` 

The latter means we wouldn't have to guard each individual function, but it would mean our `conda-forge` recipe wouldn't be able to check the import works (since tensorflow would be unavailable so this would _always_ throw an error).

The former would mean the `conda-forge` recipe can check the import, but requires a lot of code changes across 3 packages (`cellfinder`, `cellfinder-core`, `cellfinder-napari`) that we'd have to undo if we ever moved away from `tensorflow` or it became available on conda.

From the user's perspective, both approaches are the same: they get an error when they try to use `cellfinder` without `tensorflow` (just either at import or at function-call). Both cases also mean that `pip install cellfinder` _would not_ fetch tensorflow, it would need to be `pip install cellfinder[tensorflow]` (although `pip install brainglobe` would hide this wrinkle).

**Comment by adamltyson** [comment]
I'd vote for the latter.

**Comment by willGraham01** [comment]
Will do - will update [the PR](https://github.com/brainglobe/cellfinder-core/pull/185) to be the latter.

> Considering brainrender isn't on conda-forge yet, the conda metapackage is a bit dead in the water currently if it only ships 1/2 of our user facing tools.

Also I didn't realise this - I've broken that out into https://github.com/brainglobe/brainglobe-meta/issues/14

**Comment by willGraham01** [comment]
Closing as solved in https://github.com/conda-forge/cellfinder-core-feedstock/pull/14
