### ISSUE TITLE
[BGV1] Updates to `brainreg-segment`

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/BrainGlobe#36]
Subtask of #33.

### `brainglobe/brainreg-segment`

- [x] Update name to `brainglobe-segmentation`
  - [x] Update pyproject and other dependent files
  - [x] Update other dependent packages
  - [x] Check PyPI and conda are OK with the name change, then publish version

OLD TASKS (pre `brainglobe-registration`)

- Update with "final version" release. Stage as a PR against main.
  - Point users to `brainreg` repository as replacement
  - Point users to the blog post for more information
  - Tagged version should be `<v1.0`
  - Push to PyPI
- Depreciate package on PyPI
- Archive repository

**Comment by adamltyson** [comment]
> brainglobe/brainreg-segment
Should this be `brainglobe-napari`?

**Comment by adamltyson** [comment]
I know see that https://github.com/brainglobe/BrainGlobe/issues/37 exists, so I guess this issue is about `brainreg-segment`. Did we decide to merge `brainreg-segment` into brainreg?

**Comment by willGraham01** [comment]
Yeah it's in the master issue for the new release (#33): we'll have `brainreg` as one package with `core`, `segment`, and `napari` submodules (the latter two being optionals).

**Comment by adamltyson** [comment]
I'm leaning towards not merging `brainreg-segment` into `brainreg`, as it, or something like it should be compatible with the new `brainglobe-registration` plugin.

**Comment by adamltyson** [comment]
The eventual new version shouldn't be tied to `brainreg`. I'd rather keep it unbundled and with the same name for now. Once it's compatible with `brainglobe-registration` it can be called `brainglobe-segmentation` or something. 

I think when we decided to merge, we didn't have a concrete plan for the development of `brainglobe-registration`.

**Comment by adamltyson** [comment]
We could just rename it to `brainglobe-segmentation` now?

**Comment by willGraham01** [comment]
> I think when we decided to merge, we didn't have a concrete plan for the development of `brainglobe-registration`.

:thumbs_up: No problem (I did make the plan ~2 months ago so things are bound to have changed!).

> We could just rename it to `brainglobe-segmentation` now?

I'll convert this issue / open a new one to do this. Renaming right now may break some things that depend on (or look for) `brainreg-segment`. Also I'll need to check what PyPI (hence conda) thinks about renaming.

**Comment by willGraham01** [comment]
> We could just rename it to brainglobe-segmentation now?

Looks like there's a standard method for renaming on PyPI, although we do have to retire the old repository. I'm guessing we don't want to retire `brainreg-segment` as a repository due to it's GH metrics @adamltyson ?

The (quite hacky) alternatives I can think of would be:
- Publish a final release of `brainreg-segment` marking the package as decprecated and directing users to `brainglobe-segment` (which as of yet does not exist, but we'll combat that in a second).
- Rename the repository to `brainglobe-segmentation` and update the package metadata in a PR
- Merge the PR in, and publish a new release @v1.

Slightly cleaner hack:
- Rename the `brainreg-segment` repo `brainglobe-segmentation`
- Fork/clone the (now) `brainglobe-segmentation` repository, calling it `brainreg-segment`. We'd need to make sure we also preserve release notes and tags.
- Publish a release from (new) `brainreg-segment` marking depreciation etc. Then archive this fork/clone repo immediately.
- Publish the "new" `brainglobe-segmentation` package.

Slightly cleaner hack is "cleaner" because it means we won't break any of our existing dependencies on `brainreg-segment` as it'll continue to exist whilst we update everything else. Unless anyone objects, I'll go with this approach.

**Comment by adamltyson** [comment]
I think I prefer the first option, mostly because it reduces the number of repos we have and retains GH metrics etc. Also, it won't be a new tool, for now it's literally just a renaming.

**Comment by adamltyson** [comment]
Also, importantly it will mean that links (e.g in the paper) will redirect.

**Comment by willGraham01** [comment]
> Also, importantly it will mean that links (e.g in the paper) will redirect.

I wasn't aware GitHub did this :thinking: So if I rename `brainglobe/brainreg-segment` to `brainglobe/brainglobe-segmentation`, both of the following links will direct me to the same (renamed) repository?

- [Use the old link](https://github.com/brainglobe/brainreg-segment)
- [Use the new link](https://github.com/brainglobe/brainglobe-segmentation)

**Comment by adamltyson** [comment]
I assume so, if you move a repo between orgs, it will redirect.

**Comment by willGraham01** [comment]
Will pop back here and check in any case, once all the merging is done!
