### ISSUE TITLE
[Feature] `cellfinder` migration to `workflows` for BG-v1

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/BrainGlobe#45]
Subtask of #33.

# Migration of [`cellfinder`](https://github.com/brainglobe/cellfinder) to [`brainglobe-workflows`](https://github.com/brainglobe/brainglobe-workflows).

The next stage in our migration to BrainGlobe version 1 will be to move the functionality of the `cellfinder` command-line tool into the `workflows` repository, and allow it to be installed by users.

The following tasks need to be completed:

`cellfinder`
- [x] Fix outstanding bugs
- [x] Open "repository has moved PR": https://github.com/brainglobe/cellfinder/pull/261
  - [x] Update README to point to `workflows`
  - [x] Merge in and tag `cellfinder` version <1. Tagged v0.8.1.
  - [x] PUSH TO PYPI
  - [x] **_DO NOT_** archive repository. We need it open for when we replace the functionality with a merge of `cellfinder-core` and `cellfinder-napari`.
  - [x] Migrate issues to `workflows`, and tag with "old cellfinder" so context is not lost.

`workflows`
- [x] Merge in `cellfinder` history, and reconcile with existing changes https://github.com/brainglobe/brainglobe-workflows/pull/29
  - [x] Update package metadata
    - [x] CLI workflow `cellfinder` to be given a new name - @adamltyson any suggestions? 
    - [x] Give this workflow a temporary `cellfinder` alias to allow a grace period for migrating users.
  - [x] Ensure that manifest does not package our internal benchmarking tests!
  - [x] Update README to incorporate the `cellfinder` CLI function
- [x] Merge and tag a version 1 release
- [x] Push to PyPI

Dev branch: https://github.com/brainglobe/brainglobe-workflows/pull/29

`website` | https://github.com/brainglobe/brainglobe.github.io/pull/101
- [x] Blog post ready with `cellfinder` migration changes
- [x] Update v1 changelog
- [x] Update `cellfinder` docs page with redirect to workflows
- [x] Update `workflows` page (or create it if it does not exist!) with user-facing functionality
  - [x] Update developer docs if necessary with the benchmarking role of `workflows`.

**Comment by adamltyson** [comment]
> CLI workflow cellfinder to be given a new name - @adamltyson any suggestions?

Nothing good. `brainglobe-wholebrain-detection`? Can we also keep `cellfinder`, maybe with a deprecation warning?

**Comment by willGraham01** [comment]
For now we can keep `cellfinder` as the name - I can mention in the blog that a name change is on the way but keep cellfinder for the time being

**Comment by willGraham01** [comment]
Closed as successfully deployed :partying_face:
