### ISSUE TITLE
Document high-level architecture of the BG project

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/BrainGlobe#47]
Will include #16

**Comment by adamltyson** [comment]
Also document the release process (stage repo PR, docs change PR and metapackage PR) then release all in one go.

**Comment by adamltyson** [comment]
Also release cadence is ad-hoc, not date-based.

**Comment by alessandrofelder** [comment]
Also link to [core dev project](https://github.com/orgs/brainglobe/projects/2) near where the road map is in the docs, so people can see a live view of WIP.
