### ISSUE TITLE
Future plan for `cellfinder-visualize`

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/BrainGlobe#54]
[cellfinder-visualise](https://github.com/brainglobe/cellfinder-visualize) is a useful tool to analyse and visualise data output from the cellfinder command-line tool at a group level. 

Maintenance of this repo hasn't been happening, and I think it's hard to do so because:
- It's currently broken (partly due to brainrender issues)
- The cellfinder CLI isn't a top priority for us
- It's a bit different to our other tools (stand-alone GUI)

I've been thinking about what to do with it. I was thinking:
- Close all issues
- Archive
- Create an issue detailing what features we would eventually like to support in the future. Likely some combination of:
    - Scripts to analyse in `brainglobe-workflows`
    - GUI for exploratory plotting & visualisation (maybe in `brainrender-napari`)
    
Any thoughts @brainglobe/active-devs?

**Comment by willGraham01** [comment]
Why not merge the visualisation functionality into `cellfinder-napari` (or new `cellfinder` post v1) if it's meant to be used on cellfinder outputs? Or is this another "cellfinder" historical naming thing?

But I agree, particularly with `cellfinder`-CLI moving to workflows, it makes sense for the scripts to do this analysis to move there too. Even if they are only surviving in issue form for now.

**Comment by adamltyson** [comment]
`cellfinder-visualize` has been archived, and a note about its future added to the readme
