### ISSUE TITLE
[Feature] Update cellfinder to brainmapper metaissue

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/BrainGlobe#59]
Raising a metaissue to track the various things we should do following the move from `cellfinder` to `brainmapper`

* https://github.com/brainglobe/brainglobe-workflows/issues/63
* https://github.com/brainglobe/brainglobe-napari-io/issues/59
* 
cc @willGraham01

**Comment by adamltyson** [comment]
Closing this as PRs have been opened to close both the above issues.

**Comment by willGraham01** [comment]
FYI I believe GitHub is smart enough to close issues across repos. Doing something like

- [ ] https://github.com/brainglobe/brainglobe-workflows/issues/63
- [ ] https://github.com/brainglobe/brainglobe-napari-io/issues/59

in the issue body and then providing the full hyperlink in the relevant PR will track as if it were in the same repo.

**Comment by adamltyson** [comment]
Cool, thanks!
