### ISSUE TITLE
[Feature] Run CI on ARM runners too

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/BrainGlobe#63]
**Is your feature request related to a problem? Please describe.**
We have no CI guarantee that BrainGlobe installs well on ARM Macs.

**Describe the solution you'd like**
We should run at least the test for the metapackage and the workflows on ARM CI too?

**Describe alternatives you've considered**

**Additional context**
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by adamltyson** [comment]
@alessandrofelder I think this is done now right?

**Comment by alessandrofelder** [comment]
Yes :tada:
