### ISSUE TITLE
[Feature] Ensure all packages have a manifest and a manifest-checker

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/BrainGlobe#65]
Today's inspection suggests that the `test_and_deploy` workflow does not have a manifest checker in the following repos:
- [x] bg-atlasapi https://github.com/brainglobe/bg-atlasapi/pull/196
- [x] bg-atlasgen https://github.com/brainglobe/bg-atlasgen/pull/118
- [x] brainglobe-segmentation https://github.com/brainglobe/brainglobe-segmentation/pull/167
- [x] brainglobe-utils https://github.com/brainglobe/brainglobe-utils/pull/32
- [x] brainrender https://github.com/brainglobe/brainrender/pull/329
- [x] imio https://github.com/brainglobe/imio/pull/54

**Comment by willGraham01** [comment]
@alessandrofelder these should all have the linked PRs staged and ready for review. To save spamming your inbox with 5+ PR reviews, I've just tagged you here :sweat_smile:
