### ISSUE TITLE
[Feature] scheduled GH actions to keep cache

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/BrainGlobe#82]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IgorTatarnikov** [comment]
- [ ] `brainglobe-atlasapi` - https://github.com/brainglobe/brainglobe-atlasapi/pull/412
- [ ] `brainglobe-heatmap` - https://github.com/brainglobe/brainglobe-heatmap/pull/60
- [ ] `brainglobe-meta` - https://github.com/brainglobe/brainglobe-meta/pull/64
- [ ] `brainglobe-napari-io` - https://github.com/brainglobe/brainglobe-napari-io/pull/79
- [ ] `brainglobe-registration` - https://github.com/brainglobe/brainglobe-registration/pull/57
- [ ] `brainglobe-segmentation` - https://github.com/brainglobe/brainglobe-segmentation/pull/193
- [ ] `brainglobe-space` - https://github.com/brainglobe/brainglobe-space/pull/66
- [ ] `brainglobe-stitch` - https://github.com/brainglobe/brainglobe-stitch/pull/15
- [ ] `brainglobe-template-builder` - https://github.com/brainglobe/brainglobe-template-builder/pull/39
- [ ] `brainglobe-utils` - https://github.com/brainglobe/brainglobe-utils/pull/102
- [ ] `brainglobe-workflows` - https://github.com/brainglobe/brainglobe-workflows/pull/127
- [ ] `brainreg` - https://github.com/brainglobe/brainreg/pull/218
- [ ] `brainrender` - https://github.com/brainglobe/brainrender/pull/387
- [ ] `brainrender-napari` - https://github.com/brainglobe/brainrender-napari/pull/159
- [ ] `cellfinder` - https://github.com/brainglobe/cellfinder/pull/458
- [ ] `morphapi` - https://github.com/brainglobe/morphapi/pull/80

**Comment by alessandrofelder** [comment]
Amazing - thanks @IgorTatarnikov - I've merged all of these now.
